### ISSUE TITLE
Installer broken with Sample Content

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-polls#82]
During the Installer you can select ("Create sample content").

If the "polls" module is installed during the installation, following error appear. (Tested with 1.7.2)

![image](https://user-images.githubusercontent.com/4736168/107018194-690fbf00-67a0-11eb-81e6-8bb4286dc2a2.png)

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub-modules-polls/pull/83

This bug appeared after we make the column `description` required instead of `question`, so the sample Poll could not be created with empty description.
Probably the sample Poll should have some short text for the column question like:

```php
$poll->question = Yii::t('PollsModule.events', 'Where you would like to go?');
```

**Comment by luke-** [comment]
Thank you, I have added to the Question field.
